[package]
name = "fernet"
version = "0.1.0"
authors = ["Alex Gaynor <agaynor@mozilla.com>", "Ben Bangert <bbangert@mozilla.com>"]

[dependencies]
base64 = "0.9"
byteorder = "1"
openssl = "0.10"
rand = "0.4"

[dev-dependencies]
chrono = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
